spring:
  application.name: bot-platform
  profiles.active: ${ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8081}

service:
  file:
    dir: ${FILE_DIRECTORY:}
  url: ${SERVICE_URL}
---
spring:
  profiles: dev
logging:
  level:
    org.springframework.web: DEBUG
    ru.javazen.telegram.bot: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.web: WARN
    ru.javazen.telegram.bot: WARN
    org.hibernate: WARN